seed = 20
processed_data = 'data/processed/mmr_action/seed_20_stacks_50_padd_point_task_action.pkl'
train_split = 0.8
val_split = 0.1
test_split = 0.1
stacks = 50
zero_padding = 'per_data_point'
